# syntax=docker/dockerfile:1

# ---- Build stage ----
FROM node:24-alpine AS build
WORKDIR /app

# Install deps with reproducible lockfile
COPY package.json package-lock.json ./
RUN npm ci

# Inject browser keys at build time (never commit real .env to git).
ARG VITE_GOOGLE_MAPS_API_KEY
ARG VITE_FIREBASE_API_KEY
ARG VITE_CLOUDINARY_UPLOAD_MODE
ARG VITE_CLOUDINARY_CLOUD_NAME
ARG VITE_CLOUDINARY_PRESET_PROFILE_PHOTOS
ARG VITE_CLOUDINARY_PRESET_SIGNUP_DOCUMENTS
ARG VITE_CLOUDINARY_PRESET_VEHICLES
ARG VITE_CLOUDINARY_PRESET_USER_UPLOADS
ARG VITE_CLOUDINARY_UPLOAD_PRESET
ENV VITE_GOOGLE_MAPS_API_KEY=$VITE_GOOGLE_MAPS_API_KEY
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_CLOUDINARY_UPLOAD_MODE=$VITE_CLOUDINARY_UPLOAD_MODE
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME
ENV VITE_CLOUDINARY_PRESET_PROFILE_PHOTOS=$VITE_CLOUDINARY_PRESET_PROFILE_PHOTOS
ENV VITE_CLOUDINARY_PRESET_SIGNUP_DOCUMENTS=$VITE_CLOUDINARY_PRESET_SIGNUP_DOCUMENTS
ENV VITE_CLOUDINARY_PRESET_VEHICLES=$VITE_CLOUDINARY_PRESET_VEHICLES
ENV VITE_CLOUDINARY_PRESET_USER_UPLOADS=$VITE_CLOUDINARY_PRESET_USER_UPLOADS
ENV VITE_CLOUDINARY_UPLOAD_PRESET=$VITE_CLOUDINARY_UPLOAD_PRESET

# Build static site into /app/dist
COPY . .
RUN npm run build

# ---- Serve stage ----
FROM caddy:2-alpine
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /srv
EXPOSE 80
